onlyBuiltDependencies:
  - better-sqlite3

overrides:
  '@astrojs/cloudflare': $@astrojs/cloudflare
  astro: $astro
  wrangler: $wrangler

patchedDependencies:
  quikdown@1.1.1: patches/quikdown@1.1.1.patch
